#! /bin/bash

# find the longest word in a string

max_len=0
max_word=

# when 'in words' is omitted in for, for defaults to the positional parameters
for i; do
	len=$(echo $i | wc -c)
	if (( len > 0 )); then
		max_len=$len
		max_word=$i
	fi
done

echo "$1: '$max_word' ($max_len characters)"
