#! /bin/bash

# find the longest word in a list of files

# when 'in words' is omitted in for, for defaults to the positional parameters

for filename; do
	if [[ -r $filename ]]; then
		max_len=0
		max_word=
		for word in $(strings $filename); do
			len=$(echo $filename | wc -c)
			if (( len > 0 )); then
				max_len=$len
				max_word=$word
			fi
		done
		echo "$filename: '$max_word' ($max_len characters)"
	else
		echo "'$filename' is not a readable file"
	fi
done

