#! /bin/bash
#
# Program to output sysinfo

declare -r TITLE="System Information Report For $HOSTNAME"
declare -r CURRENT_TIME=$(date +"%x %r %Z")
declare -r TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_uptime() {
	cat <<- _EOF_
		<H2>System Uptime</H2>
		<PRE>$(uptime)</PRE>
		_EOF_
	return 
}

report_disk_space() {
	cat <<- _EOF_
		<H2>Disk Space Utilization</H2>
		<PRE>$(df -h)</PRE>
		_EOF_
	return
}

report_home_space() {
	# test if the user is root
	if [[ $(id -u) -eq 0 ]]; then
		cat <<- _EOF_
			<H2>Home Space Utilization (All Users)</H2>
			<PRE>$(du -sh /home/*)</PRE>
			_EOF_
		return
	else
		cat <<- _EOF_
			<H2>Home Space Utilization ($USER)</H2>
			<PRE>$(du -sh $HOME)</PRE>
		_EOF_
	fi
}

cat << _EOF_
<HTML>
	<HEAD>
		<TITLE>$TITLE</TITLE>
	</HEAD>
	<BODY>
		<H1>$TITLE</H1>
		<P>$TIME_STAMP</P>
		<P>$(report_uptime)</P>
		<P>$(report_disk_space)</P>
		<P>$(report_home_space)</P>
	</BODY>
</HTML>
_EOF_
