#! /bin/bash
#
#read-validate: validate input

invalid_input () {
	echo "Invalid input '$REPLY' ($1)" >&2
	exit 1
}

read -p "Enter a single item > "

#input is empty(invalid)
[[ -z $REPLY ]] && invalid_input "no input given"

#input is multiple items(invalid)
(( $(echo $REPLY | wc -w) > 1 )) && invalid_input "input is multiple items"

# Test scribble for myself: input is empty or multiple items in one test
#[[ -z $REPLY || $(echo $REPLY | wc -w) -gt 0 ]] && echo "Empty or multiple input"

#input a valid filename?
if [[ $REPLY =~ ^[-[:alnum:]\._]+$ ]]; then
	echo "Input is a valid filename"
else
	echo "Input is not a valid filename"
fi

#input a floating point number?
if [[ $REPLY =~ ^-?[[:digit:]]*\.[[:digit:]]+$ ]]; then
	echo "Input is a floating point number"
else
	echo "Input is not a floating point number"
fi

#input a digit?
if [[ $REPLY =~ ^-?[[:digit:]]+$ ]]; then
	echo "Input is an integer"
else
	echo "Input is not an integer"
fi

